apiVersion: autoscaling.brycemclachlan.me/v1alpha1
kind: PerPodVerticalPodAutoscaler
metadata:
  labels:
    app.kubernetes.io/name: pp-vpa
    app.kubernetes.io/managed-by: kustomize
  name: perpodverticalpodautoscaler-sample
spec:
  # TODO(user): Add fields here
