## Append samples of your project ##
resources:
- autoscaling_v1alpha1_perpodverticalpodautoscaler.yaml
- autoscaling_v1alpha1_podresourcerecommendation.yaml
- autoscaling_v1alpha1_perpodverticalpodautoscalercheckpoint.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
