//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUScalingThresholds) DeepCopyInto(out *CPUScalingThresholds) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUScalingThresholds.
func (in *CPUScalingThresholds) DeepCopy() *CPUScalingThresholds {
	if in == nil {
		return nil
	}
	out := new(CPUScalingThresholds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerLevelContention) DeepCopyInto(out *ContainerLevelContention) {
	*out = *in
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerLevelContention.
func (in *ContainerLevelContention) DeepCopy() *ContainerLevelContention {
	if in == nil {
		return nil
	}
	out := new(ContainerLevelContention)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerPolicy) DeepCopyInto(out *ContainerPolicy) {
	*out = *in
	if in.MinAllowed != nil {
		in, out := &in.MinAllowed, &out.MinAllowed
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.MaxAllowed != nil {
		in, out := &in.MaxAllowed, &out.MaxAllowed
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerPolicy.
func (in *ContainerPolicy) DeepCopy() *ContainerPolicy {
	if in == nil {
		return nil
	}
	out := new(ContainerPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRecommendation) DeepCopyInto(out *ContainerRecommendation) {
	*out = *in
	if in.LowerBound != nil {
		in, out := &in.LowerBound, &out.LowerBound
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.UncappedTarget != nil {
		in, out := &in.UncappedTarget, &out.UncappedTarget
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.UpperBound != nil {
		in, out := &in.UpperBound, &out.UpperBound
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRecommendation.
func (in *ContainerRecommendation) DeepCopy() *ContainerRecommendation {
	if in == nil {
		return nil
	}
	out := new(ContainerRecommendation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContentionHighWatermarks) DeepCopyInto(out *ContentionHighWatermarks) {
	*out = *in
	if in.PodLevel != nil {
		in, out := &in.PodLevel, &out.PodLevel
		*out = new(PodLevelContention)
		(*in).DeepCopyInto(*out)
	}
	if in.ContainerLevel != nil {
		in, out := &in.ContainerLevel, &out.ContainerLevel
		*out = make([]ContainerLevelContention, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContentionHighWatermarks.
func (in *ContentionHighWatermarks) DeepCopy() *ContentionHighWatermarks {
	if in == nil {
		return nil
	}
	out := new(ContentionHighWatermarks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfeasibleUpdateBehavior) DeepCopyInto(out *InfeasibleUpdateBehavior) {
	*out = *in
	if in.MaxSurge != nil {
		in, out := &in.MaxSurge, &out.MaxSurge
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfeasibleUpdateBehavior.
func (in *InfeasibleUpdateBehavior) DeepCopy() *InfeasibleUpdateBehavior {
	if in == nil {
		return nil
	}
	out := new(InfeasibleUpdateBehavior)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryScalingThresholds) DeepCopyInto(out *MemoryScalingThresholds) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryScalingThresholds.
func (in *MemoryScalingThresholds) DeepCopy() *MemoryScalingThresholds {
	if in == nil {
		return nil
	}
	out := new(MemoryScalingThresholds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedPeak) DeepCopyInto(out *ObservedPeak) {
	*out = *in
	if in.PodLevel != nil {
		in, out := &in.PodLevel, &out.PodLevel
		*out = new(ObservedPeakPodLevel)
		**out = **in
	}
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]ObservedPeakContainer, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedPeak.
func (in *ObservedPeak) DeepCopy() *ObservedPeak {
	if in == nil {
		return nil
	}
	out := new(ObservedPeak)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedPeakContainer) DeepCopyInto(out *ObservedPeakContainer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedPeakContainer.
func (in *ObservedPeakContainer) DeepCopy() *ObservedPeakContainer {
	if in == nil {
		return nil
	}
	out := new(ObservedPeakContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedPeakPodLevel) DeepCopyInto(out *ObservedPeakPodLevel) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedPeakPodLevel.
func (in *ObservedPeakPodLevel) DeepCopy() *ObservedPeakPodLevel {
	if in == nil {
		return nil
	}
	out := new(ObservedPeakPodLevel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerPodVerticalPodAutoscaler) DeepCopyInto(out *PerPodVerticalPodAutoscaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerPodVerticalPodAutoscaler.
func (in *PerPodVerticalPodAutoscaler) DeepCopy() *PerPodVerticalPodAutoscaler {
	if in == nil {
		return nil
	}
	out := new(PerPodVerticalPodAutoscaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PerPodVerticalPodAutoscaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerPodVerticalPodAutoscalerCheckpoint) DeepCopyInto(out *PerPodVerticalPodAutoscalerCheckpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerPodVerticalPodAutoscalerCheckpoint.
func (in *PerPodVerticalPodAutoscalerCheckpoint) DeepCopy() *PerPodVerticalPodAutoscalerCheckpoint {
	if in == nil {
		return nil
	}
	out := new(PerPodVerticalPodAutoscalerCheckpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PerPodVerticalPodAutoscalerCheckpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerPodVerticalPodAutoscalerCheckpointList) DeepCopyInto(out *PerPodVerticalPodAutoscalerCheckpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PerPodVerticalPodAutoscalerCheckpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerPodVerticalPodAutoscalerCheckpointList.
func (in *PerPodVerticalPodAutoscalerCheckpointList) DeepCopy() *PerPodVerticalPodAutoscalerCheckpointList {
	if in == nil {
		return nil
	}
	out := new(PerPodVerticalPodAutoscalerCheckpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PerPodVerticalPodAutoscalerCheckpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerPodVerticalPodAutoscalerCheckpointSpec) DeepCopyInto(out *PerPodVerticalPodAutoscalerCheckpointSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerPodVerticalPodAutoscalerCheckpointSpec.
func (in *PerPodVerticalPodAutoscalerCheckpointSpec) DeepCopy() *PerPodVerticalPodAutoscalerCheckpointSpec {
	if in == nil {
		return nil
	}
	out := new(PerPodVerticalPodAutoscalerCheckpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerPodVerticalPodAutoscalerCheckpointStatus) DeepCopyInto(out *PerPodVerticalPodAutoscalerCheckpointStatus) {
	*out = *in
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerPodVerticalPodAutoscalerCheckpointStatus.
func (in *PerPodVerticalPodAutoscalerCheckpointStatus) DeepCopy() *PerPodVerticalPodAutoscalerCheckpointStatus {
	if in == nil {
		return nil
	}
	out := new(PerPodVerticalPodAutoscalerCheckpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerPodVerticalPodAutoscalerList) DeepCopyInto(out *PerPodVerticalPodAutoscalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PerPodVerticalPodAutoscaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerPodVerticalPodAutoscalerList.
func (in *PerPodVerticalPodAutoscalerList) DeepCopy() *PerPodVerticalPodAutoscalerList {
	if in == nil {
		return nil
	}
	out := new(PerPodVerticalPodAutoscalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PerPodVerticalPodAutoscalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerPodVerticalPodAutoscalerSpec) DeepCopyInto(out *PerPodVerticalPodAutoscalerSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	if in.TargetReplicas != nil {
		in, out := &in.TargetReplicas, &out.TargetReplicas
		*out = new(int32)
		**out = **in
	}
	in.UpdatePolicy.DeepCopyInto(&out.UpdatePolicy)
	in.ResourcePolicy.DeepCopyInto(&out.ResourcePolicy)
	out.RecommenderPolicy = in.RecommenderPolicy
	out.ScalingThresholds = in.ScalingThresholds
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerPodVerticalPodAutoscalerSpec.
func (in *PerPodVerticalPodAutoscalerSpec) DeepCopy() *PerPodVerticalPodAutoscalerSpec {
	if in == nil {
		return nil
	}
	out := new(PerPodVerticalPodAutoscalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerPodVerticalPodAutoscalerStatus) DeepCopyInto(out *PerPodVerticalPodAutoscalerStatus) {
	*out = *in
	if in.DefaultRecommendation != nil {
		in, out := &in.DefaultRecommendation, &out.DefaultRecommendation
		*out = new(Recommendation)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerPodVerticalPodAutoscalerStatus.
func (in *PerPodVerticalPodAutoscalerStatus) DeepCopy() *PerPodVerticalPodAutoscalerStatus {
	if in == nil {
		return nil
	}
	out := new(PerPodVerticalPodAutoscalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodLevelContention) DeepCopyInto(out *PodLevelContention) {
	*out = *in
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodLevelContention.
func (in *PodLevelContention) DeepCopy() *PodLevelContention {
	if in == nil {
		return nil
	}
	out := new(PodLevelContention)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodLevelPolicy) DeepCopyInto(out *PodLevelPolicy) {
	*out = *in
	if in.MinAllowed != nil {
		in, out := &in.MinAllowed, &out.MinAllowed
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxAllowed != nil {
		in, out := &in.MaxAllowed, &out.MaxAllowed
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodLevelPolicy.
func (in *PodLevelPolicy) DeepCopy() *PodLevelPolicy {
	if in == nil {
		return nil
	}
	out := new(PodLevelPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodLevelRecommendation) DeepCopyInto(out *PodLevelRecommendation) {
	*out = *in
	if in.LowerBound != nil {
		in, out := &in.LowerBound, &out.LowerBound
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.UncappedTarget != nil {
		in, out := &in.UncappedTarget, &out.UncappedTarget
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.UpperBound != nil {
		in, out := &in.UpperBound, &out.UpperBound
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodLevelRecommendation.
func (in *PodLevelRecommendation) DeepCopy() *PodLevelRecommendation {
	if in == nil {
		return nil
	}
	out := new(PodLevelRecommendation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodResourceRecommendation) DeepCopyInto(out *PodResourceRecommendation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodResourceRecommendation.
func (in *PodResourceRecommendation) DeepCopy() *PodResourceRecommendation {
	if in == nil {
		return nil
	}
	out := new(PodResourceRecommendation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodResourceRecommendation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodResourceRecommendationList) DeepCopyInto(out *PodResourceRecommendationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodResourceRecommendation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodResourceRecommendationList.
func (in *PodResourceRecommendationList) DeepCopy() *PodResourceRecommendationList {
	if in == nil {
		return nil
	}
	out := new(PodResourceRecommendationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodResourceRecommendationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodResourceRecommendationSpec) DeepCopyInto(out *PodResourceRecommendationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodResourceRecommendationSpec.
func (in *PodResourceRecommendationSpec) DeepCopy() *PodResourceRecommendationSpec {
	if in == nil {
		return nil
	}
	out := new(PodResourceRecommendationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodResourceRecommendationStatus) DeepCopyInto(out *PodResourceRecommendationStatus) {
	*out = *in
	if in.ContentionHighWatermarks != nil {
		in, out := &in.ContentionHighWatermarks, &out.ContentionHighWatermarks
		*out = new(ContentionHighWatermarks)
		(*in).DeepCopyInto(*out)
	}
	if in.ObservedPeak != nil {
		in, out := &in.ObservedPeak, &out.ObservedPeak
		*out = new(ObservedPeak)
		(*in).DeepCopyInto(*out)
	}
	if in.PodLevelTarget != nil {
		in, out := &in.PodLevelTarget, &out.PodLevelTarget
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.ContainerRecommendations != nil {
		in, out := &in.ContainerRecommendations, &out.ContainerRecommendations
		*out = make([]ContainerRecommendation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AnomalyExceedSince != nil {
		in, out := &in.AnomalyExceedSince, &out.AnomalyExceedSince
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodResourceRecommendationStatus.
func (in *PodResourceRecommendationStatus) DeepCopy() *PodResourceRecommendationStatus {
	if in == nil {
		return nil
	}
	out := new(PodResourceRecommendationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Recommendation) DeepCopyInto(out *Recommendation) {
	*out = *in
	if in.PodLevelTarget != nil {
		in, out := &in.PodLevelTarget, &out.PodLevelTarget
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	in.PodLevel.DeepCopyInto(&out.PodLevel)
	if in.ContainerRecommendations != nil {
		in, out := &in.ContainerRecommendations, &out.ContainerRecommendations
		*out = make([]ContainerRecommendation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Recommendation.
func (in *Recommendation) DeepCopy() *Recommendation {
	if in == nil {
		return nil
	}
	out := new(Recommendation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecommenderPolicy) DeepCopyInto(out *RecommenderPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecommenderPolicy.
func (in *RecommenderPolicy) DeepCopy() *RecommenderPolicy {
	if in == nil {
		return nil
	}
	out := new(RecommenderPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcePolicy) DeepCopyInto(out *ResourcePolicy) {
	*out = *in
	if in.PodLevelPolicies != nil {
		in, out := &in.PodLevelPolicies, &out.PodLevelPolicies
		*out = make([]PodLevelPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ContainerPolicies != nil {
		in, out := &in.ContainerPolicies, &out.ContainerPolicies
		*out = make([]ContainerPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcePolicy.
func (in *ResourcePolicy) DeepCopy() *ResourcePolicy {
	if in == nil {
		return nil
	}
	out := new(ResourcePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingThresholds) DeepCopyInto(out *ScalingThresholds) {
	*out = *in
	out.CPU = in.CPU
	out.Memory = in.Memory
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingThresholds.
func (in *ScalingThresholds) DeepCopy() *ScalingThresholds {
	if in == nil {
		return nil
	}
	out := new(ScalingThresholds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdatePolicy) DeepCopyInto(out *UpdatePolicy) {
	*out = *in
	in.InfeasibleUpdateBehavior.DeepCopyInto(&out.InfeasibleUpdateBehavior)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdatePolicy.
func (in *UpdatePolicy) DeepCopy() *UpdatePolicy {
	if in == nil {
		return nil
	}
	out := new(UpdatePolicy)
	in.DeepCopyInto(out)
	return out
}
