apiVersion: v1
kind: ServiceAccount
metadata:
  name: pp-vpa-manager
  namespace: {{ .Values.namespace }}
---
{{- if .Values.nodeAgent.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pp-vpa-node-agent
  namespace: {{ .Values.namespace }}
{{- end }}
